group 'com.baseflow.geolocator'
version '1.0'

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.0.2'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

def dartDefines = [
        geolocatorNoPlay: 'false'
]
if (project.hasProperty('dart-defines')) {
    def defines = project.property('dart-defines')
            .split(',')
            .collectEntries { entry ->
                def decoded = new String(entry.decodeBase64(), 'UTF-8')
                def pair = decoded.split('=', 2)
                [(pair[0]): pair.length > 1 ? pair[1] : '']
            }
    dartDefines += defines
}

apply plugin: 'com.android.library'

android {
    if (project.android.hasProperty("namespace")) {
        namespace("com.baseflow.geolocator")
    }

    compileSdk flutter.compileSdkVersion

    defaultConfig {
        minSdkVersion flutter.minSdkVersion
    }
    lintOptions {
        disable 'InvalidPackage'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {

    if (dartDefines['geolocatorNoPlay'] == 'false') {
        implementation 'com.google.android.gms:play-services-location:21.2.0'
    }
    implementation 'androidx.core:core:1.18.0'

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.mockito:mockito-core:5.1.1'
}
